name: Deploy

on:
  push:
      branches:
          - main

jobs:
  deploy:
    runs-on: 
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: cd ${{ secrets.PROJECT_PATH }} && git pull && npm i && pm2 restart 0 && sudo systemctl restart nginx
        